"""법적 문서 SOT — 디스클레이머 / 약관 / 개인정보 처리방침 / 자동화 의사결정 (한·영).

텍스트는 모듈 const로 임베드 — DB row 또는 외부 파일 X (1인 8주 MVP 정합).
변경 시: (a) ``LEGAL_DOCUMENTS[(type, lang)].body`` 갱신 → (b) ``CURRENT_VERSIONS``
의 version 문자열 bump → (c) ``updated_at`` 갱신. PR diff로 변경 가시성 확보.

Public endpoint(``GET /v1/legal/{type}``)에서 노출 — 인증 무관.

Story 1.4가 ``automated-decision`` 타입 추가 — PIPA 2026.03.15 자동화 의사결정 동의
5섹션 SOT(처리 항목·이용 목적·보관 기간·제3자 제공·LLM 외부 처리). 입법예고
(R9)는 분기 1회 추적 후 텍스트·version 갱신.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Literal

# Literal 값은 hyphen 통일 — URL/SDK method/SOT dict 키 모두 동일(Story 1.4 AC13).
LegalDocType = Literal["disclaimer", "terms", "privacy", "automated-decision"]
LegalLang = Literal["ko", "en"]


@dataclass(frozen=True)
class LegalDocument:
    type: LegalDocType
    lang: LegalLang
    version: str
    title: str
    body: str  # 풀텍스트(여러 문단 \n\n 구분)
    updated_at: datetime  # ISO 8601 UTC


# --- 디스클레이머 (research 3.4 본문 정합) -----------------------------------


_DISCLAIMER_KO = """본 서비스는 일반 건강관리(웰니스) 목적의 정보 제공 서비스이며, 의료기기 또는 의학적 진단·치료·예방을 위한 도구가 아닙니다.

본 서비스가 제공하는 영양·식단 분석 및 피드백은 참고용이며, 질병의 진단, 치료, 예방 또는 의학적 조언을 대체하지 않습니다.

질병이 있거나 약물 복용 중, 임신·수유 중인 경우 반드시 의사 또는 영양사 등 전문가와 상의하시기 바랍니다.

알레르기·기저질환이 있는 사용자는 입력 정보가 누락되거나 부정확할 수 있음에 유의하시고, 응급상황 시에는 즉시 119에 연락하십시오."""


# 한국어 4 문단 fidelity 매칭을 위해 영문도 4 단락으로 재구성:
# (1) wellness purpose + not a medical device
# (2) feedback as reference + not a substitute for medical advice
# (3) consult professional if disease/medication/pregnancy
# (4) allergy/condition users + emergency note
_DISCLAIMER_EN = """This service is provided for general wellness and informational purposes only. It is not a medical device and is NOT INTENDED TO DIAGNOSE, TREAT, CURE, OR PREVENT ANY DISEASE.

The nutrition and dietary feedback generated by this service is for reference only and is not a substitute for professional medical advice, diagnosis, or treatment.

If you have a medical condition, are taking medication, or are pregnant or nursing, please consult a physician, registered dietitian, or other qualified health professional before relying on the information provided by this service.

Users with allergies or underlying conditions should be aware that input data may be incomplete or inaccurate. In an emergency, call your local emergency number immediately (in the Republic of Korea, 119)."""


# --- 약관 (한·영) -----------------------------------------------------------

_TERMS_KO = """제1조 (목적)
본 약관은 BalanceNote(이하 "회사")가 제공하는 식단 기록·영양 분석 서비스(이하 "서비스")의 이용 조건과 절차, 회사와 이용자(이하 "회원")의 권리·의무 및 책임 사항을 규정함을 목적으로 합니다.

제2조 (서비스의 성격 — 의료기기 미분류)
본 서비스는 일반 건강관리(웰니스) 목적의 정보 제공 서비스이며, 식품의약품안전처 분류상 의료기기에 해당하지 않습니다. 회사는 회원에게 의학적 진단·치료·예방을 제공하지 않으며, 본 서비스가 산출하는 모든 분석 결과는 참고 자료로만 활용되어야 합니다.

제3조 (회원 가입 및 이용)
회원 가입은 Google 계정을 통해 이루어집니다. 만 14세 미만 미성년자는 본 서비스를 이용할 수 없습니다. 회원은 정확한 정보를 제공할 의무가 있으며, 허위 정보 제공으로 발생한 결과에 대해 회사는 책임을 지지 않습니다.

제4조 (회원의 의무)
회원은 (1) 본 서비스의 분석 결과를 의학적 판단의 단독 근거로 사용하지 않고, (2) 알레르기·기저질환·임신·약물 복용 등 건강 상태에 영향을 주는 정보가 있는 경우 전문가와 상의하며, (3) 응급 상황에서는 즉시 119에 연락하는 것에 동의합니다.

제5조 (회사의 의무 및 책임 한계)
회사는 안정적인 서비스 제공을 위해 합리적인 노력을 기울입니다. 다만 본 서비스가 제공하는 분석은 LLM 기반 자동화 처리이므로 오류가 발생할 수 있으며, 회사는 분석 결과의 의학적 정확성을 보증하지 않습니다. 회사는 회원이 본 서비스의 결과에 의존해 발생한 의료적 결과에 대해 책임지지 않습니다.

제6조 (서비스 변경·중단)
회사는 운영상·기술상 필요에 따라 서비스의 일부 또는 전부를 변경하거나 중단할 수 있으며, 이 경우 회원에게 사전 고지합니다. 다만 긴급한 보안 이슈 또는 법령 준수 사유로 인한 중단은 사후 고지로 갈음할 수 있습니다.

제7조 (탈퇴 및 데이터 처리)
회원은 언제든지 회원 탈퇴를 요청할 수 있습니다. 탈퇴 시 개인정보는 별도 보존 의무가 있는 항목(약관 동의 시점 등)을 제외하고 즉시 파기됩니다. 자세한 사항은 별도의 개인정보 처리방침을 참고하시기 바랍니다.

제8조 (분쟁 해결 및 준거법)
본 약관과 관련된 분쟁은 대한민국 법령에 따르며, 회사 본점 소재지 관할 법원을 1심 관할 법원으로 합니다."""


_TERMS_EN = """Article 1 (Purpose)
These Terms govern the conditions and procedures for using the meal-logging and nutrition-analysis service (the "Service") provided by BalanceNote (the "Company"), as well as the rights, obligations, and responsibilities of the Company and its users ("Members").

Article 2 (Nature of the Service — Not a Medical Device)
The Service is provided for general wellness and informational purposes only. It is not classified as a medical device under Korean Ministry of Food and Drug Safety regulations. The Company does not provide medical diagnosis, treatment, or prevention, and all analytical output of the Service must be treated as reference material only.

Article 3 (Membership and Use)
Membership is established through a Google account. Persons under 14 years of age may not use the Service. Members are responsible for providing accurate information; the Company is not liable for consequences arising from inaccurate or false information.

Article 4 (Member Obligations)
Members agree (1) not to use the Service's analytical output as the sole basis for medical decisions, (2) to consult a qualified professional regarding allergies, underlying conditions, pregnancy, medication, or other health-affecting factors, and (3) to contact local emergency services immediately in an emergency (in the Republic of Korea, 119).

Article 5 (Company Obligations and Limitation of Liability)
The Company makes reasonable efforts to provide a stable Service. However, because the Service relies on LLM-based automated processing, errors may occur, and the Company does not guarantee the medical accuracy of any analysis. The Company is not liable for medical outcomes arising from a Member's reliance on the Service's output.

Article 6 (Modifications and Suspensions)
The Company may modify or suspend all or part of the Service for operational or technical reasons, with prior notice to Members. Suspensions due to urgent security issues or legal compliance may be communicated after the fact.

Article 7 (Withdrawal and Data Handling)
Members may request withdrawal at any time. Upon withdrawal, personal data is destroyed promptly, except for items subject to separate retention obligations (e.g., timestamps of terms acceptance). For details, refer to the Privacy Policy.

Article 8 (Disputes and Governing Law)
Disputes arising under these Terms are governed by the laws of the Republic of Korea, with the court of jurisdiction over the Company's principal office having first-instance jurisdiction.

This is a courtesy translation; the Korean original prevails."""


# --- 개인정보 처리방침 (한·영) ----------------------------------------------

_PRIVACY_KO = """본 개인정보 처리방침은 BalanceNote(이하 "회사")가 회원의 개인정보를 수집·이용·보관·파기하는 방식과 회원의 권리 행사 절차를 규정합니다. 본 처리방침은 「개인정보 보호법」(이하 "PIPA") 제22조 동의 별도 분리 의무 및 제23조 민감정보 별도 동의 의무에 정합합니다.

1. 수집 항목
- 일반 개인정보: Google 계정 식별자(sub), 이메일, 표시 이름, 프로필 사진 URL.
- 민감정보(PIPA 제23조 별도 동의): 체중, 신장, 알레르기 정보, 식사 기록, 건강 목표.
- 동의 시점 감사 흔적: 동의 시각, IP 주소(`request.client.host`), User-Agent 문자열(최대 512자 절단). 본 항목은 PIPA 고지 의무에 따라 명시합니다.

2. 이용 목적
- 회원 식별 및 인증.
- 영양·식단 분석 피드백 제공(LLM 기반 자동화 처리 — 별도 동의 항목으로 분리됨).
- BMR/TDEE 등 영양 추정값 계산.
- 알레르기 기반 안전 가드(allergen 단락) 적용.
- 약관·개인정보 동의 이력 보존(법적 보존 의무).

3. 보관 기간
- 회원 탈퇴 요청 시 개인정보를 즉시 파기합니다. 다만 약관·개인정보 동의 시점 등 별도 법적 보존 의무가 있는 항목은 보존 기간이 만료될 때까지 격리 보관 후 파기합니다.

4. 제3자 제공 및 국외 이전
- 제3자 제공: 없음.
- 국외 이전: LLM 분석 호출 시 마스킹된 식단 텍스트가 OpenAI(미국) 또는 Anthropic(미국) API에 송신됩니다. 분석 트레이스는 LangSmith(미국)에 저장됩니다. 본 이전은 분석 기능 제공에 필수적이며, Story 1.4 자동화 의사결정 동의의 별도 동의 대상에 해당합니다.
- 운영 옵저버빌리티(LangSmith Inc., 미국): 본 서비스는 LangSmith Inc.(미국)로 LLM 호출 트레이스(노드 input/output, latency, token 사용량)를 송신합니다. 송신 전 민감정보(체중·신장·알레르기·식단 raw text·사용자 식별자)를 마스킹 처리해 PII 송신 0을 보장하며, 운영·품질 추적 목적에 한해 사용됩니다. 거부 시 회원 가입 자체는 가능하나, 시스템 운영 효율 일부가 제한됩니다.

5. 개인정보 책임자 및 권리 행사
- 개인정보 책임자: BalanceNote 운영자(연락처는 서비스 내 설정 화면 또는 운영 문서에 별도 명시).
- 회원은 언제든지 본인 정보의 열람·정정·삭제·처리정지를 요청할 수 있으며, 회사는 PIPA에 따라 지체 없이 처리합니다."""


_PRIVACY_EN = """This Privacy Policy describes how BalanceNote (the "Company") collects, uses, retains, and destroys Members' personal information, and how Members may exercise their rights. This Policy aligns with Article 22 (separate consent for distinct purposes) and Article 23 (separate consent for sensitive personal information) of the Personal Information Protection Act ("PIPA").

1. Information Collected
- General personal information: Google account identifier (sub), email address, display name, profile picture URL.
- Sensitive personal information (PIPA Article 23 — requires separate consent): weight, height, allergy information, meal records, health goals.
- Consent audit trail: timestamp of consent, IP address (request.client.host), User-Agent string (truncated to 512 characters). Disclosed pursuant to PIPA notification obligations.

2. Purposes of Use
- Member identification and authentication.
- Provision of nutrition and dietary analysis feedback (LLM-based automated processing — covered by a separate consent item).
- Calculation of estimated values such as BMR and TDEE.
- Application of allergen-based safety guards.
- Retention of records of consent to terms and privacy policy (legal retention).

3. Retention Period
- Personal information is destroyed promptly upon withdrawal. However, items subject to separate legal retention (such as timestamps of terms acceptance) are retained in isolation until the applicable retention period expires, after which they are destroyed.

4. Third-Party Provision and International Transfers
- Third-party provision: none.
- International transfers: When LLM analysis is performed, masked meal text is transmitted to the OpenAI API (United States) or the Anthropic API (United States). Analysis traces are stored with LangSmith (United States). These transfers are essential to the analytical functionality and are subject to the separate automated-decision consent introduced in Story 1.4.
- Operational observability (LangSmith Inc., United States): the Service transmits LLM-call traces (per-node input/output, latency, token usage) to LangSmith Inc. (United States). Sensitive information (weight, height, allergies, raw meal text, user identifiers) is masked before transmission so that zero PII is sent, and the data is used solely for operational and quality monitoring. If a Member declines, account registration remains available, although some operational efficiency of the Service may be reduced.

5. Privacy Officer and Rights Exercise
- Privacy Officer: the BalanceNote operator (contact details are listed separately in the Service settings or operational documentation).
- Members may at any time request access, correction, deletion, or suspension of processing of their personal information; the Company will respond without delay in accordance with PIPA.

This is a courtesy translation; the Korean original prevails."""


# --- 자동화 의사결정 동의서 (Story 1.4, PIPA 2026.03.15) ----------------------
#
# 5섹션 명세: 처리 항목 / 이용 목적 / 보관 기간 / 제3자 제공 / LLM 외부 처리.
# 한국어 본문은 PRD §C2 + epics.md Story 1.4 AC + research 2.5(법제처 입법예고)
# 결합. 영문은 1:1 번역 + 1줄 번역 디스클레이머. 입법예고는 분기 1회 추적
# (R9 SOP) — 텍스트·version은 본 시점 SOT, 변경 시 ``_VERSION_AUTOMATED_DECISION``
# 별도 const로 분기 가능.

_AUTOMATED_DECISION_KO = """본 동의서는 BalanceNote(이하 "회사")가 회원의 식단·건강 데이터를 LLM 기반 자동화 처리로 분석하여 개인화된 영양·식단 피드백을 산출하는 의사결정에 대한 별도 동의를 규정합니다. 본 동의는 「개인정보 보호법」(이하 "PIPA") 제22조의2(2026.03.15 시행)에 따른 자동화된 결정에 대한 정보주체의 동의 의무에 정합합니다. 입법예고 추적: https://www.moleg.go.kr/lawinfo/makingInfo.mo?lawSeq=81114

## 1. 처리 항목
체중, 신장, 알레르기 정보, 식사 기록(텍스트·사진 OCR 결과), 건강 목표(체중 감량/유지/증량 등). 본 항목은 LLM 호출 직전 NFR-O2 마스킹 processor가 PII(이메일 주소·체중 수치·식단 raw_text·알레르기 식별자)를 송신 전 마스킹 처리합니다.

## 2. 이용 목적
LangGraph 6노드 + Self-RAG 파이프라인을 통한 자동화된 영양·식단 분석, ``fit_score`` 적합도 산출, 인용 근거형 피드백 메시지 생성. 본 자동화 처리의 결과는 회원의 의학적 의사결정을 대체하지 않으며, 디스클레이머에 명시된 한계가 모두 적용됩니다.

## 3. 보관 기간
분석 결과(``meal_analyses`` 테이블) 및 LangSmith 트레이스는 회원 탈퇴 요청 시 즉시 파기됩니다. 동의 시점 및 철회 시점 기록은 PIPA 외 관련법(예: 전자상거래법)이 보존을 요구하는 기간 동안 격리 보관 후 파기됩니다.

## 4. 제3자 제공 및 국외 이전
제3자 제공: 없음.
국외 이전: 본 자동화 처리는 OpenAI(미국, GPT-4o-mini 계열)와 Anthropic(미국, Claude 계열) API에 마스킹된 데이터를 송신하며, 분석 트레이스는 LangSmith(미국)에 저장됩니다. 본 이전은 자동화된 영양 분석 기능 제공에 필수적입니다.

## 5. LLM 외부 처리
회사는 ``adapters/openai.py`` 및 ``adapters/anthropic.py`` 모듈을 통해 위 LLM API를 호출합니다. 송신 직전 ``mask_processor``가 PII를 마스킹하며, ``LANGCHAIN_TRACING_V2`` 환경변수가 활성화된 경우 마스킹된 trace가 LangSmith에 송신됩니다. 회원은 본 자동화 처리에 동의하지 않을 권리가 있으며, 미동의 또는 동의 철회 시 영양·식단 분석 기능이 비활성화됩니다(다른 기능에는 영향 없음). 동의 철회는 설정 화면에서 언제든 수행할 수 있습니다."""


_AUTOMATED_DECISION_EN = """This consent governs separate authorization for BalanceNote (the "Company") to analyze a Member's meal and health data through LLM-based automated processing in order to produce personalized nutrition and dietary feedback. This consent aligns with Article 22-2 (effective 2026.03.15) of the Personal Information Protection Act ("PIPA"), which requires data-subject consent for automated decisions. Legislative-notice tracking: https://www.moleg.go.kr/lawinfo/makingInfo.mo?lawSeq=81114

## 1. Items Processed
Weight, height, allergy information, meal records (text and photo-OCR output), and health goals (e.g., weight loss/maintenance/gain). Immediately before each LLM call, the NFR-O2 masking processor masks PII (email address, weight values, raw meal text, allergen identifiers) prior to transmission.

## 2. Purposes of Use
Automated nutrition and dietary analysis through a LangGraph 6-node + Self-RAG pipeline, computation of the ``fit_score`` suitability metric, and generation of citation-backed feedback messages. The output of this automated processing does not substitute for a Member's medical decisions, and all limitations stated in the Disclaimer apply.

## 3. Retention Period
Analysis output (``meal_analyses`` table) and LangSmith traces are destroyed promptly upon a Member's withdrawal request. Records of consent and withdrawal timestamps are retained in isolation for the period required by laws other than PIPA (e.g., e-commerce statutes), then destroyed.

## 4. Third-Party Provision and International Transfers
Third-party provision: none.
International transfers: This automated processing transmits masked data to the OpenAI (United States, GPT-4o-mini family) and Anthropic (United States, Claude family) APIs, and analysis traces are stored with LangSmith (United States). These transfers are essential to providing the automated nutrition-analysis functionality.

## 5. LLM External Processing
The Company invokes the above LLM APIs through the ``adapters/openai.py`` and ``adapters/anthropic.py`` modules. The ``mask_processor`` masks PII immediately before transmission, and when the ``LANGCHAIN_TRACING_V2`` environment variable is enabled, masked traces are sent to LangSmith. Members have the right to decline this automated processing; if consent is not granted or is later withdrawn, the nutrition and dietary analysis features are disabled (other features are unaffected). Withdrawal can be performed at any time from the settings screen.

This is a courtesy translation; the Korean original prevails."""


# --- SOT 매핑 ---------------------------------------------------------------


# Story 3.8 — privacy 본문에 LangSmith 운영 옵저버빌리티 단락 추가 (NFR-O5).
# 본 bump는 *minor* — PII 송신 0이 명시되어 정보주체 권리 영향이 낮아 강제 재동의는
# 본 스토리 OUT(spec AC9 정합). 운영 시점에 hwan이 재동의 UX 흐름을 별도 결정.
_UPDATED_AT = datetime(2026, 5, 4, 0, 0, 0, tzinfo=UTC)
_VERSION_KO = "ko-2026-05-04"
_VERSION_EN = "en-2026-05-04"


LEGAL_DOCUMENTS: dict[tuple[LegalDocType, LegalLang], LegalDocument] = {
    ("disclaimer", "ko"): LegalDocument(
        type="disclaimer",
        lang="ko",
        version=_VERSION_KO,
        title="면책 조항",
        body=_DISCLAIMER_KO,
        updated_at=_UPDATED_AT,
    ),
    ("disclaimer", "en"): LegalDocument(
        type="disclaimer",
        lang="en",
        version=_VERSION_EN,
        title="Disclaimer",
        body=_DISCLAIMER_EN,
        updated_at=_UPDATED_AT,
    ),
    ("terms", "ko"): LegalDocument(
        type="terms",
        lang="ko",
        version=_VERSION_KO,
        title="이용 약관",
        body=_TERMS_KO,
        updated_at=_UPDATED_AT,
    ),
    ("terms", "en"): LegalDocument(
        type="terms",
        lang="en",
        version=_VERSION_EN,
        title="Terms of Service",
        body=_TERMS_EN,
        updated_at=_UPDATED_AT,
    ),
    ("privacy", "ko"): LegalDocument(
        type="privacy",
        lang="ko",
        version=_VERSION_KO,
        title="개인정보 처리방침",
        body=_PRIVACY_KO,
        updated_at=_UPDATED_AT,
    ),
    ("privacy", "en"): LegalDocument(
        type="privacy",
        lang="en",
        version=_VERSION_EN,
        title="Privacy Policy",
        body=_PRIVACY_EN,
        updated_at=_UPDATED_AT,
    ),
    # Story 1.4 — hyphen 키 통일(Literal/URL/SOT 키 1:1).
    ("automated-decision", "ko"): LegalDocument(
        type="automated-decision",
        lang="ko",
        version=_VERSION_KO,
        title="자동화 의사결정 동의서",
        body=_AUTOMATED_DECISION_KO,
        updated_at=_UPDATED_AT,
    ),
    ("automated-decision", "en"): LegalDocument(
        type="automated-decision",
        lang="en",
        version=_VERSION_EN,
        title="Automated Decision Consent",
        body=_AUTOMATED_DECISION_EN,
        updated_at=_UPDATED_AT,
    ),
}


# 기본 동의 4종 — POST /v1/users/me/consents 시 클라이언트가 보낸 *_version이
# 본 매핑과 일치해야 통과(미일치 시 409 ConsentVersionMismatchError).
#
# `sensitive_personal_info`는 자체 ``LegalDocument`` 항목이 없고 ``privacy`` 텍스트의
# *민감정보* 단락을 공유한다(PIPA 22조·23조 별도 동의 의무는 *체크박스 분리 + 시각 분리
# + 별도 단락*으로 충족 — AC1·AC13 정합). 따라서 본 키도 ``_VERSION_KO``를 공유하며,
# 클라이언트는 ``privacy.version``을 ``sensitive_personal_info_version`` 필드에 그대로
# 전송한다. 향후 민감정보 텍스트를 *분리 SOT*로 승격할 경우 ``LegalDocType`` Literal에
# ``sensitive_personal_info`` 추가 + 본 키 독립 bump.
CURRENT_VERSIONS: dict[str, str] = {
    "disclaimer": _VERSION_KO,
    "terms": _VERSION_KO,
    "privacy": _VERSION_KO,
    "sensitive_personal_info": _VERSION_KO,
    # Story 1.4 — hyphen 키 통일(Literal/URL과 1:1). 입법예고(R9) 추적 후 분기 1회
    # 갱신 시 본 키만 독립 bump 가능(``_VERSION_AUTOMATED_DECISION_KO`` 별도 const).
    "automated-decision": _VERSION_KO,
}
