/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Login */
        post: operations["google_login_v1_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/admin/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Exchange */
        post: operations["admin_exchange_v1_auth_admin_exchange_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health Profile
         * @description 프로필 조회 — 인증만(자기 정보 조회는 동의 무관, deps.py 주석 정합).
         *
         *     미입력 사용자(``profile_completed_at IS NULL``) → 200 + 6 필드 NULL +
         *     ``allergies=[]`` + ``profile_completed_at=null``. 404 미사용.
         */
        get: operations["get_health_profile_v1_users_me_profile_get"];
        put?: never;
        /**
         * Submit Health Profile
         * @description 프로필 입력 — 7컬럼 update + ``profile_completed_at = now()`` set.
         *
         *     ``users`` row는 OAuth 시점(Story 1.2)에 이미 존재 — INSERT 분기 X. 항상 200.
         *     재입력(이미 입력된 사용자가 다시 POST)도 200 + 갱신값 반영 + ``profile_completed_at``
         *     갱신(*최신 프로필 기록 시점*. 과거 입력 history는 audit_logs Story 7.3 책임).
         *
         *     ``UPDATE ... RETURNING``으로 race-free 응답 — commit 후 별도 SELECT 시
         *     동시 다른 device POST가 끼어들면 응답이 *방금 보낸 값*이 아닌 *마지막 commit
         *     값*이 되는 race를 차단. ``profile_completed_at`` / ``updated_at`` 양쪽 모두
         *     DB-side ``func.now()`` 단일 시계 — Python ``datetime.now()`` 와의 clock skew 회피.
         *
         *     응답 build는 ``commit`` *이전*에 수행 — AsyncSession은 ``commit`` 후 모든 객체를
         *     expire 시키므로, expired 객체 속성 접근이 lazy-load를 trigger해
         *     ``sqlalchemy.exc.MissingGreenlet`` (async context lazy-load 금지) 가능.
         *     RETURNING으로 메모리에 이미 로드된 데이터를 commit 전에 직렬화 후 commit.
         *
         *     Story 1.6 — ``onboarded_at = func.coalesce(User.onboarded_at, func.now())``로 단일
         *     UPDATE 안에서 *기존 NULL이면 now() set, 이미 set이면 그대로* (멱등). Story 5.1
         *     프로필 수정 시점에도 ``onboarded_at``은 변경되지 않아 *최초 온보딩 시점*이 보존됨.
         *     ``onboarded_first_time`` 로깅은 update 직전 ORM 객체 값으로 판별(NFR-S5: user_id만
         *     raw, 다른 민감정보 X).
         */
        post: operations["submit_health_profile_v1_users_me_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Consents */
        get: operations["get_consents_v1_users_me_consents_get"];
        put?: never;
        /** Submit Consents */
        post: operations["submit_consents_v1_users_me_consents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me/consents/automated-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant Automated Decision Consent
         * @description PIPA 2026.03.15 자동화 의사결정 동의 grant — 항상 200(부분 update 의미).
         *
         *     재동의 케이스(이전에 ``automated_decision_revoked_at IS NOT NULL`` 사용자)도 안전:
         *     UPSERT set_에 ``automated_decision_revoked_at = None``로 명시 reset.
         *     INSERT 분기(이론상 불가 — 본 endpoint 진입 가드가 basic 4종 통과 강제)에서는 basic
         *     4 컬럼을 함께 set하지 않는다(``has_all_basic_consents=false`` 반환으로 클라이언트가
         *     onboarding 흐름 재진입).
         */
        post: operations["grant_automated_decision_consent_v1_users_me_consents_automated_decision_post"];
        /**
         * Revoke Automated Decision Consent
         * @description 동의 철회 — ``automated_decision_revoked_at = now()`` set, ``_consent_at`` 보존.
         *
         *     row 없음 또는 ``automated_decision_consent_at IS NULL``(미동의) 또는 이미 철회된 상태
         *     (``automated_decision_revoked_at IS NOT NULL``) →
         *     ``AutomatedDecisionConsentNotGrantedError`` (404). 이미 철회된 상태에서 재호출 시
         *     *철회는 idempotent 가 아닌* 명시 분기 — 두 번째 DELETE 가 200 으로 통과하면 원본
         *     철회 시각(PIPA audit) 을 새 ``now()`` 로 덮어쓴다.
         *
         *     구현: ``UPDATE ... WHERE ... RETURNING`` 단일 쿼리 — SELECT-then-UPDATE TOCTOU
         *     race 회피 + DB round-trip 1회. WHERE 매칭 실패 시 row 반환 0건 → 404.
         */
        delete: operations["revoke_automated_decision_consent_v1_users_me_consents_automated_decision_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/legal/{doc_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Legal Document
         * @description SOT 매핑(`LEGAL_DOCUMENTS`)에서 직접 조회 — DB 호출 없음.
         */
        get: operations["get_legal_document_v1_legal__doc_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Meals
         * @description 자기 식단 목록 조회 — 인증만 (PIPA Art.35).
         *
         *     ``WHERE user_id = current_user.id AND deleted_at IS NULL`` 강제 — 다른 사용자
         *     노출 / soft-deleted 노출 회귀 차단.
         *
         *     Story 2.4 — 날짜 필터는 ``Asia/Seoul`` TZ 자정 boundary로 해석합니다 (W50 해소,
         *     D1 결정). ``from_date=2026-04-30`` → ``2026-04-30T00:00:00+09:00`` 이상,
         *     ``to_date=2026-04-30`` → ``2026-05-01T00:00:00+09:00`` 미만. KST 0-9시 식단 누락
         *     차단(``ate_at='2026-04-30T03:00:00+09:00'`` UTC ``2026-04-29T18:00:00Z``이
         *     ``from_date=2026-04-30``에 포함). 다중 TZ 지원은 Growth NFR-L4.
         *
         *     Story 2.4 — ORDER BY 분기 (D2 결정). 날짜 필터 활성 시 ``ate_at ASC``(시간순 —
         *     아침→저녁, epic AC line 558), 미적용 시 ``ate_at DESC``(최근 식단 우선, Story 8
         *     cursor pagination forward-compat). partial index ``idx_meals_user_id_ate_at_active``
         *     는 양방향 hit.
         *
         *     ``cursor`` 비-null 송신은 거부 (P18 / D2 결정 — silent 무시 → 무한 루프 footgun
         *     차단). ``next_cursor``는 항상 ``null``. ``analysis_summary``는 항상 ``null``
         *     (Story 3.x ``meal_analyses`` JOIN 책임 — Story 2.4 baseline은 forward-compat 슬롯만).
         */
        get: operations["list_meals_v1_meals_get"];
        put?: never;
        /**
         * Create Meal
         * @description 식단 생성 — INSERT + RETURNING으로 race-free 응답.
         *
         *     ``ate_at`` 미지정 시 ``func.now()`` fallback (DB-side 단일 시계). 응답 build는
         *     ``commit`` *이전*에 — expired 객체 lazy-load 회피 (Story 1.5 패턴).
         *
         *     Story 2.2: ``image_key`` ownership 검증 + 사진-only 입력 시 ``raw_text`` placeholder
         *     fallback (`PHOTO_ONLY_RAW_TEXT_PLACEHOLDER`). Story 2.3 OCR이 결과로 덮어씀.
         *
         *     Story 2.5 (W46 흡수): ``Idempotency-Key`` 헤더 송신 시 같은 키 재송신은
         *     ``200 OK`` 응답 (RFC 9110 idempotent retry — resource는 이미 존재). 첫 INSERT는
         *     그대로 ``201 Created``. ``Idempotency-Key``는 *키 == 한 번* 시맨틱 — 같은 키 +
         *     다른 ``raw_text``는 첫 응답을 그대로 replay (body diff 무시 — Stripe/Toss 표준 정합).
         */
        post: operations["create_meal_v1_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meals/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Meal
         * @description 식단 soft delete — ``UPDATE meals SET deleted_at = now() WHERE ... RETURNING id``.
         *
         *     물리 삭제 X (soft delete만). 30일 grace + 물리 파기는 Story 5.2 책임. 이미
         *     soft-deleted된 meal은 404 (멱등 *조회* 결과 일관성 + enumeration 차단).
         */
        delete: operations["delete_meal_v1_meals__meal_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Meal
         * @description 식단 수정 — 단일 SQL ``update().where(id, user_id, deleted_at IS NULL).returning()``.
         *
         *     소유권 미일치 / 존재 X / soft-deleted 모두 동일 404 + ``code=meals.not_found``
         *     (enumeration 차단).
         *
         *     Story 2.2:
         *     - ``image_key`` 추가 — *명시 `null` = 클리어*, *키 부재 = no-op* (Pydantic v2
         *       `model_fields_set`로 absent vs explicit null 구분).
         *     - ``image_key`` ownership 검증 — None이 아닐 때만 (None=클리어는 검증 대상 X).
         *     - PATCH 후 *raw_text + image_key 둘 다 None* invariant — `raw_text` DB NOT NULL +
         *       Story 2.1 D4 시맨틱(`raw_text=null` 송신은 no-op)으로 SQL 레벨 unreachable.
         *       별도 가드 X (YAGNI, 추가 SELECT round-trip 0).
         */
        patch: operations["update_meal_v1_meals__meal_id__patch"];
        trace?: never;
    };
    "/v1/meals/images/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue Presigned Upload
         * @description R2 presigned PUT URL + 표시용 public URL 한 쌍 발급.
         *
         *     HTTP 200 채택 — presign은 *리소스 생성*이 아닌 *short-lived 토큰 발급*
         *     (stateless — DB row 0). 201은 부적절. ``Idempotency-Key`` 헤더는 *수신만*
         *     허용 — 매 호출 새 키 발급(중복 방지 의미 부재 / 같은 key 반복 송신해도 매
         *     호출 새 image_key 반환).
         *
         *     에러 흐름:
         *     - 401 — `auth.access_token.invalid` (`current_user`)
         *     - 403 — `consent.basic.missing` (`require_basic_consents`)
         *     - 400 — `validation.error` (Pydantic Literal/Field) 또는
         *       `meals.image.upload_invalid` (adapter `R2UploadValidationError`)
         *     - 503 — `meals.image.r2_unconfigured` (`R2NotConfiguredError`)
         *
         *     P1 — sync boto3 호출(`generate_presigned_url`)은 ``asyncio.to_thread``로
         *     격리해 event-loop block 회피.
         */
        post: operations["issue_presigned_upload_v1_meals_images_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meals/images/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Meal Image Endpoint
         * @description 식단 사진(R2 업로드 완료) → GPT-4o Vision OCR → ``parsed_items`` 응답.
         *
         *     HTTP 200 채택 — parse는 *리소스 생성*이 아닌 *idempotent 분석 호출*(stateless —
         *     DB row 0). 매 호출 새 Vision 호출 + 새 응답(temperature=0.0 강제로 변동성 최소화).
         *     캐시(`cache:llm:{sha256(image_key)}`)는 Story 8 polish.
         *
         *     에러 흐름:
         *     - 401 — `auth.access_token.invalid` (`current_user`)
         *     - 403 — `consent.basic.missing` (`require_basic_consents`)
         *     - 400 — `validation.error` (Pydantic regex) /
         *       `meals.image.foreign_key_rejected` / `meals.image.not_uploaded`
         *     - 503 — `meals.image.r2_unconfigured` (R2 환경변수) /
         *       `meals.image.ocr_image_url_missing` (R2 public URL 없음) /
         *       `meals.image.ocr_unavailable` (Vision API 장애)
         *     - 502 — `meals.image.ocr_payload_invalid` (Vision schema 위반)
         *
         *     검증 순서: (1) ownership(prefix), (2) R2 head_object HEAD-check (P21), (3)
         *     Vision 호출. ownership 실패 시 R2 round-trip 회피 (cost + latency).
         */
        post: operations["parse_meal_image_endpoint_v1_meals_images_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analysis/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Analysis
         * @description ``POST /v1/analysis/stream`` — SSE 분석 스트림.
         *
         *     흐름: 3 게이트 통과 → meal 소유권 검증 → analysis_service 가용성 확인 → SSE generator
         *     진입(progress → service.run → token chunk → citation → UPSERT → done).
         *
         *     rate limit ``10/minute`` per-IP은 ``Depends(enforce_langgraph_rate_limit)``으로 wire.
         */
        post: operations["stream_analysis_v1_analysis_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analysis/clarify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Clarification
         * @description ``POST /v1/analysis/clarify`` — Story 3.4 needs_clarification resume (SSE 응답).
         *
         *     동일 ChatStreaming UI 재사용 위해 SSE 응답. ``analysis_service.aresume(thread_id,
         *     user_input={"selected_value": ...})`` 호출(Story 3.4 SOT). aresume 내부
         *     ``force_llm_parse=True`` 자동 주입.
         */
        post: operations["resume_clarification_v1_analysis_clarify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analysis/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll Analysis
         * @description ``GET /v1/analysis/{meal_id}`` — polling fallback (status discriminator envelope).
         *
         *     응답 분기:
         *     - state.feedback 존재 → 200 + ``{"status": "done", "result": {...}}``
         *     - state.needs_clarification → 200 + ``{"status": "needs_clarification", "options": [...]}``
         *     - state.node_errors → 200 + ``{"status": "error", "problem": {...RFC 7807}}``
         *     - state empty + meal 존재 → 202 + ``{"status": "in_progress", "phase": "queued"}``
         *
         *     *PIPA 자동화 의사결정 동의는 미요구* — polling = 단순 *조회*. PIPA Art.35 정보주체
         *     권리 정합(deps.py:182-187 SOT). 정상 분석 *호출*만 자동화 의사결정 동의 강제.
         */
        get: operations["poll_analysis_v1_analysis__meal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe — 프로세스 생존 신호만 응답. DB·Redis 의존성 없음.
         *
         *     k8s liveness 컨벤션상 외부 의존성과 분리되어야 함. DB 일시 장애가 컨테이너 재시작
         *     루프를 유발하지 않도록. DB·Redis·pgvector 확인은 /readyz에서 담당.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe — Postgres + Redis + pgvector extension 확인 (타임아웃 적용).
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminExchangeResponse
         * @description `admin_access_token`은 mobile에서만 채움(secure-store 저장).
         *
         *     Web 흐름에서는 `bn_admin_access` httpOnly 쿠키만 발급되고 body는 `null` —
         *     JS에서 token 노출 차단(NFR-S2).
         */
        AdminExchangeResponse: {
            /** Admin Access Token */
            admin_access_token: string | null;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /**
         * AnalysisClarifyRequest
         * @description ``POST /v1/analysis/clarify`` body — Story 3.4 ``ClarificationOption.value`` 정합.
         *
         *     ``selected_value``는 ``min_length=1`` + ``max_length=80``(Story 3.4 SOT). Pydantic이
         *     1차 게이트, ``aresume`` 호출 시점에 빈 값 catch(``AnalysisClarifyValidationError``)는
         *     *adapter-level defensive double-gate*.
         */
        AnalysisClarifyRequest: {
            /**
             * Meal Id
             * Format: uuid
             */
            meal_id: string;
            /** Selected Value */
            selected_value: string;
        };
        /**
         * AnalysisStreamRequest
         * @description ``POST /v1/analysis/stream`` body — extra="forbid"로 silent unknown 차단.
         */
        AnalysisStreamRequest: {
            /**
             * Meal Id
             * Format: uuid
             */
            meal_id: string;
        };
        /**
         * AutomatedDecisionGrantRequest
         * @description Story 1.4 — POST /v1/users/me/consents/automated-decision body.
         */
        AutomatedDecisionGrantRequest: {
            /** Automated Decision Version */
            automated_decision_version: string;
        };
        /** ConsentStatusResponse */
        ConsentStatusResponse: {
            /** Disclaimer Acknowledged At */
            disclaimer_acknowledged_at: string | null;
            /** Terms Consent At */
            terms_consent_at: string | null;
            /** Privacy Consent At */
            privacy_consent_at: string | null;
            /** Sensitive Personal Info Consent At */
            sensitive_personal_info_consent_at: string | null;
            /** Disclaimer Version */
            disclaimer_version: string | null;
            /** Terms Version */
            terms_version: string | null;
            /** Privacy Version */
            privacy_version: string | null;
            /** Sensitive Personal Info Version */
            sensitive_personal_info_version: string | null;
            /** Basic Consents Complete */
            basic_consents_complete: boolean;
            /** Automated Decision Consent At */
            automated_decision_consent_at: string | null;
            /** Automated Decision Revoked At */
            automated_decision_revoked_at: string | null;
            /** Automated Decision Version */
            automated_decision_version: string | null;
            /** Automated Decision Consent Complete */
            automated_decision_consent_complete: boolean;
        };
        /** ConsentSubmitRequest */
        ConsentSubmitRequest: {
            /** Disclaimer Version */
            disclaimer_version: string;
            /** Terms Version */
            terms_version: string;
            /** Privacy Version */
            privacy_version: string;
            /** Sensitive Personal Info Version */
            sensitive_personal_info_version: string;
        };
        /** GoogleLoginRequest */
        GoogleLoginRequest: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "mobile" | "web";
            /** Code */
            code: string;
            /** Redirect Uri */
            redirect_uri: string;
            /** Code Verifier */
            code_verifier: string;
        };
        /**
         * GoogleLoginResponseMobile
         * @description 모바일은 토큰을 응답 body로 반환(secure-store에서 보관).
         */
        GoogleLoginResponseMobile: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            user: components["schemas"]["UserPublic"];
        };
        /**
         * GoogleLoginResponseWeb
         * @description Web은 토큰을 httpOnly 쿠키로만 반환 — body에는 user만.
         */
        GoogleLoginResponseWeb: {
            user: components["schemas"]["UserPublic"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthProfileResponse
         * @description ``POST/GET /v1/users/me/profile`` 응답 — 7 필드.
         *
         *     ``allergies``는 NULL → ``[]`` 빈 배열로 응답(클라이언트 분기 단순화).
         *     ``weight_kg``는 DB ``Decimal`` → JSON wire format ``float`` 직렬화.
         */
        HealthProfileResponse: {
            /** Age */
            age: number | null;
            /** Weight Kg */
            weight_kg: number | null;
            /** Height Cm */
            height_cm: number | null;
            /** Activity Level */
            activity_level: ("sedentary" | "light" | "moderate" | "active" | "very_active") | null;
            /** Health Goal */
            health_goal: ("weight_loss" | "muscle_gain" | "maintenance" | "diabetes_management") | null;
            /** Allergies */
            allergies: string[];
            /** Profile Completed At */
            profile_completed_at: string | null;
        };
        /**
         * HealthProfileSubmitRequest
         * @description ``POST /v1/users/me/profile`` body — 6 입력 필드 (profile_completed_at은 backend-managed).
         *
         *     범위 검증은 Pydantic ``Field(ge=, le=)``로 1차, DB CHECK 제약이 2차(double gate).
         *     ``allergies`` 22종 검증은 ``field_validator``에서 ``normalize_allergens()`` 호출 —
         *     invalid 항목 발견 시 ``ValueError`` raise → Pydantic ``ValidationError`` →
         *     글로벌 핸들러가 RFC 7807 400 + ``code=validation.error``.
         */
        HealthProfileSubmitRequest: {
            /** Age */
            age: number;
            /** Weight Kg */
            weight_kg: number;
            /** Height Cm */
            height_cm: number;
            /**
             * Activity Level
             * @enum {string}
             */
            activity_level: "sedentary" | "light" | "moderate" | "active" | "very_active";
            /**
             * Health Goal
             * @enum {string}
             */
            health_goal: "weight_loss" | "muscle_gain" | "maintenance" | "diabetes_management";
            /** Allergies */
            allergies?: string[];
        };
        /** LegalDocumentResponse */
        LegalDocumentResponse: {
            /**
             * Type
             * @enum {string}
             */
            type: "disclaimer" | "terms" | "privacy" | "automated-decision";
            /**
             * Lang
             * @enum {string}
             */
            lang: "ko" | "en";
            /** Version */
            version: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /**
         * MealAnalysisSummary
         * @description 식단 AI 분석 요약 — Epic 3 ``meal_analyses`` 테이블 1:1 매핑 forward-compat 슬롯.
         *
         *     Story 2.4 — Pydantic 인터페이스만 정의. 본 스토리 baseline은 ``MealResponse.analysis_summary``
         *     *항상 None*(서버 join X) — 실제 채움은 Story 3.3 / 3.5. 별도 endpoint 분리는
         *     yagni — list 응답에 슬롯 통합(Story 3.x perf hardening 시점에 분리 검토).
         *
         *     fields:
         *
         *     - ``fit_score``: 0-100 (FR21 정합).
         *     - ``fit_score_label``: 5단계 텍스트 라벨 — NFR-A4 색약 대응. ``allergen_violation``
         *       (FR22 알레르기 0점 단락) / ``low`` / ``moderate`` / ``good`` / ``excellent``.
         *     - ``macros``: 식약처 OpenAPI 표준 키.
         *     - ``feedback_summary``: 1줄 피드백 (max 120) — FR23 인용형 풀 텍스트는 ``[meal_id].tsx``
         *       채팅(Story 3.7 SSE).
         */
        MealAnalysisSummary: {
            /** Fit Score */
            fit_score: number;
            /**
             * Fit Score Label
             * @enum {string}
             */
            fit_score_label: "allergen_violation" | "low" | "moderate" | "good" | "excellent";
            macros: components["schemas"]["MealMacros"];
            /** Feedback Summary */
            feedback_summary: string;
        };
        /**
         * MealCreateRequest
         * @description ``POST /v1/meals`` body — `extra="forbid"`로 silent unknown field 차단.
         *
         *     Story 2.1: ``raw_text`` 빈 문자열·whitespace-only 거부 (1차 게이트, trim 정규화 —
         *     모바일 ``zod.trim()``과 wire 단일화 / P1). ``ate_at`` 미지정 시 DB-side ``now()``
         *     fallback (server_default). 미래 시점 거부는 도메인 룰 미존재 (catch-up 시나리오
         *     허용). naive datetime은 거부 (P19 / D3 결정).
         *
         *     Story 2.2: ``raw_text``를 *Optional*로 변경 — *최소 한 종(`raw_text` 또는
         *     `image_key`) 필요*. 사진-only 입력 허용. ``image_key`` ownership 검증은 라우터
         *     inline (Pydantic field_validator는 user context 미접근).
         */
        MealCreateRequest: {
            /** Raw Text */
            raw_text?: string | null;
            /** Ate At */
            ate_at?: string | null;
            /** Image Key */
            image_key?: string | null;
            /** Parsed Items */
            parsed_items?: components["schemas"]["ParsedMealItem"][] | null;
        };
        /**
         * MealImageParseRequest
         * @description ``POST /v1/meals/images/parse`` body — image_key만 (forward-compat: 향후
         *     `model` / `language_hint` 등 옵션 추가 시 body schema 확장).
         *
         *     `image_key` regex는 Story 2.2 `meals.py:_IMAGE_KEY_PATTERN` 재사용 — wire 단일화.
         */
        MealImageParseRequest: {
            /** Image Key */
            image_key: string;
        };
        /**
         * MealImageParseResponse
         * @description 5 필드 — Vision OCR 결과 + 계산된 low_confidence 플래그 + 운영 지표.
         *
         *     `low_confidence`는 모바일 forced confirmation UI 분기 입력 (items 빈 배열 또는
         *     min(confidence) < 0.6). `model`은 운영 가시성(향후 `gpt-4o-mini` 다운그레이드
         *     검토 시 필드 비교).
         */
        MealImageParseResponse: {
            /** Image Key */
            image_key: string;
            /** Parsed Items */
            parsed_items: components["schemas"]["ParsedMealItem"][];
            /** Low Confidence */
            low_confidence: boolean;
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /**
         * MealImagePresignRequest
         * @description ``POST /v1/meals/images/presign`` body.
         *
         *     `content_type`은 Literal로 1차 게이트 — Pydantic이 router 진입 전 차단(400 +
         *     `code=validation.error`). adapter는 *defensive double-gate* (signature 호출
         *     경로 보호).
         *
         *     `content_length`는 Field `ge=1, le=10*1024*1024` — 0 byte 또는 음수, 10 MB
         *     초과 거부.
         */
        MealImagePresignRequest: {
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "image/jpeg" | "image/png" | "image/webp" | "image/heic" | "image/heif";
            /** Content Length */
            content_length: number;
        };
        /**
         * MealImagePresignResponse
         * @description 5 필드 — 라우터가 ``r2_adapter.PresignedUpload`` dataclass에서 직렬화.
         */
        MealImagePresignResponse: {
            /** Upload Url */
            upload_url: string;
            /** Image Key */
            image_key: string;
            /** Public Url */
            public_url: string;
            /** Expires At */
            expires_at: string;
            /** Content Type */
            content_type: string;
        };
        /**
         * MealListResponse
         * @description 식단 목록 응답. ``next_cursor``는 본 스토리에서 항상 ``null`` (Story 2.4 입력).
         */
        MealListResponse: {
            /** Meals */
            meals: components["schemas"]["MealResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * MealMacros
         * @description 식단 매크로 영양 정보 — 식약처 OpenAPI 표준 키 정합 (architecture line 289).
         *
         *     Story 2.4 — Epic 3 forward-compat. 모든 필드 ``ge=0`` non-negative 단언. 본 스토리
         *     baseline은 *항상 None*(서버 join X) — 실제 채움은 Story 3.3 (`meal_analyses` 테이블
         *     + LangGraph 노드 + ``app/domain/fit_score.py`` 알고리즘) / Story 3.5 (fit_score 룰).
         */
        MealMacros: {
            /** Carbohydrate G */
            carbohydrate_g: number;
            /** Protein G */
            protein_g: number;
            /** Fat G */
            fat_g: number;
            /** Energy Kcal */
            energy_kcal: number;
        };
        /**
         * MealResponse
         * @description 식단 단건 응답 — 11 필드 (Story 2.1+2.2+2.3 10 + Story 2.4 analysis_summary).
         *
         *     ``deleted_at`` / ``image_key`` / ``image_url`` / ``parsed_items`` /
         *     ``analysis_summary`` NULL 시에도 키 유지 (스키마 안정성, architecture line 481).
         *     ``image_url``은 derived — `image_key` 있으면 `_resolve_public_url(image_key)`,
         *     없으면 None (`_meal_to_response` helper에서 계산).
         *
         *     Story 2.4 — ``analysis_summary``는 본 스토리 baseline *항상 None*(서버 join X).
         *     Story 3.x가 ``meal_analyses`` JOIN으로 채움.
         */
        MealResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Raw Text */
            raw_text: string;
            /**
             * Ate At
             * Format: date-time
             */
            ate_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Image Key */
            image_key: string | null;
            /** Image Url */
            image_url: string | null;
            /** Parsed Items */
            parsed_items: components["schemas"]["ParsedMealItem"][] | null;
            analysis_summary: components["schemas"]["MealAnalysisSummary"] | null;
        };
        /**
         * MealUpdateRequest
         * @description ``PATCH /v1/meals/{meal_id}`` body — 모든 필드 absent 시 400 (최소 1 필드 필수).
         *
         *     Story 2.1: ``raw_text=null``과 *필드 부재*는 동일 처리 (no-op, D4 결정). naive
         *     ``ate_at`` 거부 (P19 / D3 결정). raw_text는 trim 정규화 (P1).
         *
         *     Story 2.2: ``image_key`` 추가 — *명시 `null` = 클리어 (사진 제거)*, *키 부재 = no-op*.
         *     Pydantic v2 `model_fields_set`로 absent vs explicit null 구분 (라우터 inline).
         *     `_at_least_one_field` model_validator는 *값이 아닌 송신 여부* 검사 (D4 explicit
         *     null 시맨틱 보존 — 단순 `is None` 검사로는 의미 손실).
         */
        MealUpdateRequest: {
            /** Raw Text */
            raw_text?: string | null;
            /** Ate At */
            ate_at?: string | null;
            /** Image Key */
            image_key?: string | null;
            /** Parsed Items */
            parsed_items?: components["schemas"]["ParsedMealItem"][] | null;
        };
        /**
         * ParsedMealItem
         * @description OCR Vision 추출 단일 항목.
         *
         *     - ``name``: 한국어 표준 음식명 (예: ``"짜장면"``). 빈 문자열 거부 (Vision 출력
         *       신뢰 + 사용자 확인 카드 후 편집 가능). max_length 50 — DB jsonb + UI 표시
         *       합리적 상한. CR P7 fix(2026-04-30): 콤마 거부 — ``_format_parsed_items_to_raw_text``
         *       가 ``", "``로 항목을 join하므로 name 콤마 포함 시 raw_text boundary 모호 (예:
         *       ``"감자, 양파" + "500g"`` → ``"감자, 양파 500g"`` 잘못 분리). 사용자 편집 round-trip
         *       안정성 보장.
         *     - ``quantity``: 추정 양 (예: ``"1인분"`` / ``"4개"`` / ``"300g"``). 빈 quantity
         *       허용 (*"바나나"* 처럼 양 없는 항목 대응) — ``min_length=0``.
         *     - ``confidence``: 0.0~1.0 신뢰도 — 임계값 0.6 미만은 모바일 forced confirmation.
         */
        ParsedMealItem: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: string;
            /** Confidence */
            confidence: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /** RefreshResponseMobile */
        RefreshResponseMobile: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /** UserMeResponse */
        UserMeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Picture Url */
            picture_url: string | null;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at: string | null;
            /** Onboarded At */
            onboarded_at: string | null;
            /** Profile Completed At */
            profile_completed_at: string | null;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Picture Url */
            picture_url: string | null;
            /** Role */
            role: string;
            /** Profile Completed At */
            profile_completed_at: string | null;
            /** Onboarded At */
            onboarded_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    google_login_v1_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleLoginResponseMobile"] | components["schemas"]["GoogleLoginResponseWeb"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bn_refresh?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponseMobile"] | {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bn_refresh?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_exchange_v1_auth_admin_exchange_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_refresh?: string | null;
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminExchangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_profile_v1_users_me_profile_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_health_profile_v1_users_me_profile_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthProfileSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_consents_v1_users_me_consents_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_consents_v1_users_me_consents_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_automated_decision_consent_v1_users_me_consents_automated_decision_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutomatedDecisionGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_automated_decision_consent_v1_users_me_consents_automated_decision_delete: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_legal_document_v1_legal__doc_type__get: {
        parameters: {
            query?: {
                lang?: "ko" | "en";
            };
            header?: never;
            path: {
                doc_type: "disclaimer" | "terms" | "privacy" | "automated-decision";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meals_v1_meals_get: {
        parameters: {
            query?: {
                from_date?: string | null;
                to_date?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meal_v1_meals_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealCreateRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay (Story 2.5 — same Idempotency-Key) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"];
                };
            };
            /** @description Validation failed (raw_text / image_key / Idempotency-Key) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Idempotency-Key collides with soft-deleted meal */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_v1_meals__meal_id__delete: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                meal_id: string;
            };
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meal_v1_meals__meal_id__patch: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                meal_id: string;
            };
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_presigned_upload_v1_meals_images_presign_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealImagePresignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealImagePresignResponse"];
                };
            };
            /** @description Validation error or unsupported content type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Basic consents required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Image upload service unavailable (R2 unconfigured) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    parse_meal_image_endpoint_v1_meals_images_parse_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealImageParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealImageParseResponse"];
                };
            };
            /** @description Validation error or image not uploaded / foreign key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Basic consents required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Image OCR returned invalid payload */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Image OCR or R2 service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stream_analysis_v1_analysis_stream_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisStreamRequest"];
            };
        };
        responses: {
            /** @description SSE 스트림 응답 (text/event-stream) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description PIPA basic 또는 automated_decision consent 미통과 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description meal 미존재 / 비소유 / soft-deleted (analysis.meal.not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description rate limit 초과 (analysis.rate_limit.exceeded) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description checkpointer 미가동 (analysis.checkpointer.unavailable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resume_clarification_v1_analysis_clarify_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisClarifyRequest"];
            };
        };
        responses: {
            /** @description SSE 스트림 응답 (clarify resume) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description PIPA consent 미통과 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description meal 미존재 / 비소유 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description selected_value 빈 값 또는 형식 위반 (analysis.clarify.invalid) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description rate limit 초과 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description checkpointer 미가동 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    poll_analysis_v1_analysis__meal_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                meal_id: string;
            };
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description 분석 상태 envelope (status: done|needs_clarification|error) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 분석 진행 중 (status: in_progress) + Retry-After hint */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PIPA basic consent 미통과 (automated_decision은 미요구) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description meal 미존재 / 비소유 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description checkpointer 미가동 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
