/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Login */
        post: operations["google_login_v1_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/admin/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Exchange */
        post: operations["admin_exchange_v1_auth_admin_exchange_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health Profile
         * @description 프로필 조회 — 인증만(자기 정보 조회는 동의 무관, deps.py 주석 정합).
         *
         *     미입력 사용자(``profile_completed_at IS NULL``) → 200 + 6 필드 NULL +
         *     ``allergies=[]`` + ``profile_completed_at=null``. 404 미사용.
         */
        get: operations["get_health_profile_v1_users_me_profile_get"];
        put?: never;
        /**
         * Submit Health Profile
         * @description 프로필 입력 — 7컬럼 update + ``profile_completed_at = now()`` set.
         *
         *     ``users`` row는 OAuth 시점(Story 1.2)에 이미 존재 — INSERT 분기 X. 항상 200.
         *     재입력(이미 입력된 사용자가 다시 POST)도 200 + 갱신값 반영 + ``profile_completed_at``
         *     갱신(*최신 프로필 기록 시점*. 과거 입력 history는 audit_logs Story 7.3 책임).
         */
        post: operations["submit_health_profile_v1_users_me_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Consents */
        get: operations["get_consents_v1_users_me_consents_get"];
        put?: never;
        /** Submit Consents */
        post: operations["submit_consents_v1_users_me_consents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me/consents/automated-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant Automated Decision Consent
         * @description PIPA 2026.03.15 자동화 의사결정 동의 grant — 항상 200(부분 update 의미).
         *
         *     재동의 케이스(이전에 ``automated_decision_revoked_at IS NOT NULL`` 사용자)도 안전:
         *     UPSERT set_에 ``automated_decision_revoked_at = None``로 명시 reset.
         *     INSERT 분기(이론상 불가 — 본 endpoint 진입 가드가 basic 4종 통과 강제)에서는 basic
         *     4 컬럼을 함께 set하지 않는다(``has_all_basic_consents=false`` 반환으로 클라이언트가
         *     onboarding 흐름 재진입).
         */
        post: operations["grant_automated_decision_consent_v1_users_me_consents_automated_decision_post"];
        /**
         * Revoke Automated Decision Consent
         * @description 동의 철회 — ``automated_decision_revoked_at = now()`` set, ``_consent_at`` 보존.
         *
         *     row 없음 또는 ``automated_decision_consent_at IS NULL``(미동의) 또는 이미 철회된 상태
         *     (``automated_decision_revoked_at IS NOT NULL``) →
         *     ``AutomatedDecisionConsentNotGrantedError`` (404). 이미 철회된 상태에서 재호출 시
         *     *철회는 idempotent 가 아닌* 명시 분기 — 두 번째 DELETE 가 200 으로 통과하면 원본
         *     철회 시각(PIPA audit) 을 새 ``now()`` 로 덮어쓴다.
         *
         *     구현: ``UPDATE ... WHERE ... RETURNING`` 단일 쿼리 — SELECT-then-UPDATE TOCTOU
         *     race 회피 + DB round-trip 1회. WHERE 매칭 실패 시 row 반환 0건 → 404.
         */
        delete: operations["revoke_automated_decision_consent_v1_users_me_consents_automated_decision_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/legal/{doc_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Legal Document
         * @description SOT 매핑(`LEGAL_DOCUMENTS`)에서 직접 조회 — DB 호출 없음.
         */
        get: operations["get_legal_document_v1_legal__doc_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe — 프로세스 생존 신호만 응답. DB·Redis 의존성 없음.
         *
         *     k8s liveness 컨벤션상 외부 의존성과 분리되어야 함. DB 일시 장애가 컨테이너 재시작
         *     루프를 유발하지 않도록. DB·Redis·pgvector 확인은 /readyz에서 담당.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe — Postgres + Redis + pgvector extension 확인 (타임아웃 적용).
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminExchangeResponse
         * @description `admin_access_token`은 mobile에서만 채움(secure-store 저장).
         *
         *     Web 흐름에서는 `bn_admin_access` httpOnly 쿠키만 발급되고 body는 `null` —
         *     JS에서 token 노출 차단(NFR-S2).
         */
        AdminExchangeResponse: {
            /** Admin Access Token */
            admin_access_token: string | null;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /**
         * AutomatedDecisionGrantRequest
         * @description Story 1.4 — POST /v1/users/me/consents/automated-decision body.
         */
        AutomatedDecisionGrantRequest: {
            /** Automated Decision Version */
            automated_decision_version: string;
        };
        /** ConsentStatusResponse */
        ConsentStatusResponse: {
            /** Disclaimer Acknowledged At */
            disclaimer_acknowledged_at: string | null;
            /** Terms Consent At */
            terms_consent_at: string | null;
            /** Privacy Consent At */
            privacy_consent_at: string | null;
            /** Sensitive Personal Info Consent At */
            sensitive_personal_info_consent_at: string | null;
            /** Disclaimer Version */
            disclaimer_version: string | null;
            /** Terms Version */
            terms_version: string | null;
            /** Privacy Version */
            privacy_version: string | null;
            /** Sensitive Personal Info Version */
            sensitive_personal_info_version: string | null;
            /** Basic Consents Complete */
            basic_consents_complete: boolean;
            /** Automated Decision Consent At */
            automated_decision_consent_at: string | null;
            /** Automated Decision Revoked At */
            automated_decision_revoked_at: string | null;
            /** Automated Decision Version */
            automated_decision_version: string | null;
            /** Automated Decision Consent Complete */
            automated_decision_consent_complete: boolean;
        };
        /** ConsentSubmitRequest */
        ConsentSubmitRequest: {
            /** Disclaimer Version */
            disclaimer_version: string;
            /** Terms Version */
            terms_version: string;
            /** Privacy Version */
            privacy_version: string;
            /** Sensitive Personal Info Version */
            sensitive_personal_info_version: string;
        };
        /** GoogleLoginRequest */
        GoogleLoginRequest: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "mobile" | "web";
            /** Code */
            code: string;
            /** Redirect Uri */
            redirect_uri: string;
            /** Code Verifier */
            code_verifier: string;
        };
        /**
         * GoogleLoginResponseMobile
         * @description 모바일은 토큰을 응답 body로 반환(secure-store에서 보관).
         */
        GoogleLoginResponseMobile: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            user: components["schemas"]["UserPublic"];
        };
        /**
         * GoogleLoginResponseWeb
         * @description Web은 토큰을 httpOnly 쿠키로만 반환 — body에는 user만.
         */
        GoogleLoginResponseWeb: {
            user: components["schemas"]["UserPublic"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthProfileResponse
         * @description ``POST/GET /v1/users/me/profile`` 응답 — 7 필드.
         *
         *     ``allergies``는 NULL → ``[]`` 빈 배열로 응답(클라이언트 분기 단순화).
         *     ``weight_kg``는 DB ``Decimal`` → JSON wire format ``float`` 직렬화.
         */
        HealthProfileResponse: {
            /** Age */
            age: number | null;
            /** Weight Kg */
            weight_kg: number | null;
            /** Height Cm */
            height_cm: number | null;
            /** Activity Level */
            activity_level: ("sedentary" | "light" | "moderate" | "active" | "very_active") | null;
            /** Health Goal */
            health_goal: ("weight_loss" | "muscle_gain" | "maintenance" | "diabetes_management") | null;
            /** Allergies */
            allergies: string[];
            /** Profile Completed At */
            profile_completed_at: string | null;
        };
        /**
         * HealthProfileSubmitRequest
         * @description ``POST /v1/users/me/profile`` body — 6 입력 필드 (profile_completed_at은 backend-managed).
         *
         *     범위 검증은 Pydantic ``Field(ge=, le=)``로 1차, DB CHECK 제약이 2차(double gate).
         *     ``allergies`` 22종 검증은 ``field_validator``에서 ``normalize_allergens()`` 호출 —
         *     invalid 항목 발견 시 ``ValueError`` raise → Pydantic ``ValidationError`` →
         *     글로벌 핸들러가 RFC 7807 400 + ``code=validation.error``.
         */
        HealthProfileSubmitRequest: {
            /** Age */
            age: number;
            /** Weight Kg */
            weight_kg: number;
            /** Height Cm */
            height_cm: number;
            /**
             * Activity Level
             * @enum {string}
             */
            activity_level: "sedentary" | "light" | "moderate" | "active" | "very_active";
            /**
             * Health Goal
             * @enum {string}
             */
            health_goal: "weight_loss" | "muscle_gain" | "maintenance" | "diabetes_management";
            /** Allergies */
            allergies?: string[];
        };
        /** LegalDocumentResponse */
        LegalDocumentResponse: {
            /**
             * Type
             * @enum {string}
             */
            type: "disclaimer" | "terms" | "privacy" | "automated-decision";
            /**
             * Lang
             * @enum {string}
             */
            lang: "ko" | "en";
            /** Version */
            version: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /** RefreshResponseMobile */
        RefreshResponseMobile: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /** UserMeResponse */
        UserMeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Picture Url */
            picture_url: string | null;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at: string | null;
            /** Onboarded At */
            onboarded_at: string | null;
            /** Profile Completed At */
            profile_completed_at: string | null;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Picture Url */
            picture_url: string | null;
            /** Role */
            role: string;
            /** Profile Completed At */
            profile_completed_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    google_login_v1_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleLoginResponseMobile"] | components["schemas"]["GoogleLoginResponseWeb"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bn_refresh?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponseMobile"] | {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bn_refresh?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_exchange_v1_auth_admin_exchange_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_refresh?: string | null;
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminExchangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_profile_v1_users_me_profile_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_health_profile_v1_users_me_profile_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthProfileSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_consents_v1_users_me_consents_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_consents_v1_users_me_consents_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_automated_decision_consent_v1_users_me_consents_automated_decision_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutomatedDecisionGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_automated_decision_consent_v1_users_me_consents_automated_decision_delete: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                bn_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_legal_document_v1_legal__doc_type__get: {
        parameters: {
            query?: {
                lang?: "ko" | "en";
            };
            header?: never;
            path: {
                doc_type: "disclaimer" | "terms" | "privacy" | "automated-decision";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
